const SET_VISIBLE_FILTER = 'SET_VISIBLE_FILTER';
const SELECT_ITEM = 'SELECT_ITEM';
const POST_REQUEST = 'POST_REQUEST';
const POST_SUCCESS = 'POST_SUCCESS';

export {
    SET_VISIBLE_FILTER,
    SELECT_ITEM,
    POST_REQUEST,
    POST_SUCCESS,
};