const POST_REQUEST_STOCK_DETAILS = 'POST_REQUEST_STOCK_DETAILS';
const POST_SUCCESS_STOCK_DETAILS = 'POST_SUCCESS_STOCK_DETAILS';

export {
    
    POST_REQUEST_STOCK_DETAILS,
    POST_SUCCESS_STOCK_DETAILS,
};